version: '3.8'
services:
  evaluation:
    image: jitgen_eval:${TAG:-latest}
    container_name: evaluation_container
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./results:/app/results