[project]
name = "jitgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.64",
    "lark>=1.2.2",
    "pydantic>=2.11.5",
]

[dependency-groups]
test = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.0.0",
]
evaluation = [
    "langchain-community>=0.3.24",
    "langchain-ollama>=0.3.3",
    "langgraph>=0.4.8",
    "python-dotenv>=1.1.0",
    "datasets>=3.3.2",
    "frozenlist==1.6.0",
    "huggingface>=0.0.1",
    "pydantic-settings>=2.9.1",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.3",
    "seaborn>=0.13.2",
]
