[project]
name = "openai-example"
version = "0.1.0"
description = "Example of using JitGen with LLM using OpenAI library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jitgen",
    "langsmith>=0.10.17",
    "openai>=2.53.0",
    "python-dotenv>=1.2.2",
]

[tool.uv.sources]
jitgen = { path = "../../libs/jitgen", editable = true }
