"""
LangChain Integration Example

This example shows how to use JitGen with LangChain to execute
code generated by LLMs incrementally.

Requirements:
- Ollama running locally with a model (e.g., llama3.2)
- Or modify to use your preferred LLM provider
"""

import asyncio
from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from jitgen_langchain.python import create_python_jitgen_parser


async def main():
    """Example using JitGen with LangChain and Ollama."""
    print("=" * 60)
    print("JitGen LangChain Integration Example")
    print("=" * 60)
    
    # Check if Ollama is available
    try:
        llm = ChatOllama(model="llama3.2", temperature=0)
    except Exception as e:
        print(f"\n⚠ Error: Could not connect to Ollama: {e}")
        print("\nTo run this example:")
        print("1. Install Ollama: https://ollama.ai")
        print("2. Pull a model: ollama pull llama3.2")
        print("3. Run this script again\n")
        return
    
    # Create a prompt template
    prompt = ChatPromptTemplate.from_messages([
        ("system", "You are a helpful Python programming assistant. Generate Python code to solve the given task. Always wrap code in ```python code blocks."),
        ("human", "Task: {task}")
    ])
    
    # Create the JitGen parser
    parser = create_python_jitgen_parser()
    
    # Build the chain: prompt -> LLM -> JitGen parser -> string output
    chain = prompt | llm | parser | StrOutputParser()
    
    # Example task
    task = "Print the first 5 prime numbers"
    
    print(f"\nTask: {task}")
    print("\nGenerating and executing code incrementally...")
    print("-" * 60)
    
    try:
        async for output in chain.astream({"task": task}):
            if output:
                print(output, end="", flush=True)
        print("-" * 60)
        print("\n✓ Execution complete!")
        print("  Notice how output appeared as code was generated and executed.")
    except Exception as e:
        print(f"\n✗ Error during execution: {e}")


if __name__ == "__main__":
    asyncio.run(main())

